<?php

/**
 * HMAC Server for the Site Export API.
 *
 * This class verifies the HMAC-authenticated requests generated by
 * Site_Export_HMAC_Client. It validates the required X-Auth-* headers,
 * checks request freshness, and confirms the received request payload
 * matches the signed content hash.
 */
final class Site_Export_HMAC_Server {

    /** @var string */
    private $secret;

    /** @var int */
    private $timestamp_tolerance;

    public function __construct(string $secret, int $timestamp_tolerance = 300) {
        $this->secret = $secret;
        $this->timestamp_tolerance = $timestamp_tolerance;
    }

    /**
     * Verify a request using explicit inputs.
     *
     * Returns null on success, or an error string on failure.
     * When $files is non-empty, the content hash is computed from uploaded file
     * contents rather than $body so multipart uploads verify consistently.
     */
    public function verify(array $headers = [], ?string $body = null, array $files = [], ?float $now = null): ?string {
        return $this->verify_content_hash_callback(
            $headers,
            function () use ($body, $files): string {
                return $this->compute_received_content_hash($body, $files);
            },
            $now
        );
    }

    /**
     * Verify a request when the caller already streamed and hashed the body.
     *
     * This keeps large raw uploads out of PHP memory while preserving the same
     * timestamp, nonce, content-hash, and HMAC checks as verify().
     */
    public function verify_content_hash(array $headers, string $received_content_hash, ?float $now = null): ?string {
        return $this->verify_content_hash_callback(
            $headers,
            function () use ($received_content_hash): string {
                return $received_content_hash;
            },
            $now
        );
    }

    /**
     * Validate all cheap authentication inputs before reading request bodies.
     *
     * Large multipart uploads can live on slow disks. More importantly, unauthenticated
     * callers should not be able to force the server to hash those files before the
     * request has passed timestamp, nonce, and signature checks.
     */
    private function verify_content_hash_callback(array $headers, callable $received_content_hash, ?float $now = null): ?string {
        $signature = $this->get_header($headers, 'X-Auth-Signature');
        $nonce = $this->get_header($headers, 'X-Auth-Nonce');
        $timestamp = $this->get_header($headers, 'X-Auth-Timestamp');
        $signed_content_hash = $this->get_header($headers, 'X-Auth-Content-Hash');

        if ($signature === null || $signature === '') {
            return 'Missing X-Auth-Signature header';
        }
        if ($nonce === null || $nonce === '') {
            return 'Missing X-Auth-Nonce header';
        }
        if ($timestamp === null || $timestamp === '') {
            return 'Missing X-Auth-Timestamp header';
        }
        if ($signed_content_hash === null || $signed_content_hash === '') {
            return 'Missing X-Auth-Content-Hash header';
        }

        if (!is_numeric($timestamp)) {
            return 'Invalid timestamp format';
        }

        $request_time = (float) $timestamp;
        $current_time = $now ?? microtime(true);
        $time_diff = abs($current_time - $request_time);

        if ($time_diff > $this->timestamp_tolerance) {
            return sprintf(
                'Request timestamp expired. Difference: %.2f seconds, max allowed: %d seconds',
                $time_diff,
                $this->timestamp_tolerance
            );
        }

        if (strlen($nonce) < 16) {
            return 'Nonce must be at least 16 characters';
        }

        $expected_signature = hash_hmac('sha256', $nonce . $timestamp . $signed_content_hash, $this->secret);
        if (!hash_equals($expected_signature, $signature)) {
            return 'HMAC signature verification failed';
        }

        try {
            $actual_content_hash = $received_content_hash();
        } catch (RuntimeException $e) {
            return $e->getMessage();
        }

        if (!hash_equals($signed_content_hash, $actual_content_hash)) {
            return 'Content hash mismatch: body was modified in transit';
        }

        return null;
    }

    /**
     * Verify the current PHP request when the caller streamed php://input to disk.
     */
    public function verify_global_content_hash(string $received_content_hash, ?float $now = null): ?string {
        return $this->verify_content_hash($this->collect_global_headers(), $received_content_hash, $now);
    }

    /**
     * Verify the current PHP request using superglobals.
     *
     * Returns null on success, or an error string on failure.
     */
    public function verify_globals(?float $now = null): ?string {
        $body = file_get_contents('php://input');
        if ($body === false) {
            $body = '';
        }

        return $this->verify($this->collect_global_headers(), $body, $_FILES, $now);
    }

    private function collect_global_headers(): array {
        $headers = [];

        if (function_exists('getallheaders')) {
            $all_headers = getallheaders();
            if (is_array($all_headers)) {
                $headers = $all_headers;
            }
        }

        foreach ($_SERVER as $key => $value) {
            if (strpos($key, 'HTTP_') !== 0 || !is_string($value)) {
                continue;
            }

            $headers[$key] = $value;
        }

        return $headers;
    }

    private function get_header(array $headers, string $name): ?string {
        foreach ($headers as $key => $value) {
            if (!is_string($value)) {
                continue;
            }

            if (strcasecmp($key, $name) === 0) {
                return $value;
            }

            if (strcasecmp($key, 'HTTP_' . strtoupper(str_replace('-', '_', $name))) === 0) {
                return $value;
            }
        }

        return null;
    }

    private function compute_received_content_hash(?string $body, array $files): string {
        if (empty($files)) {
            return hash('sha256', $body ?? '');
        }

        $context = hash_init('sha256');
        $this->append_file_hashes($context, $files);
        return hash_final($context);
    }

    /**
     * Walk a PHP $_FILES-style structure in a deterministic order.
     */
    private function append_file_hashes($context, array $files): void {
        ksort($files);

        foreach ($files as $file_info) {
            if (!is_array($file_info)) {
                continue;
            }

            $tmp_name = $file_info['tmp_name'] ?? null;
            $this->append_tmp_name_hash($context, $tmp_name);
        }
    }

    private function append_tmp_name_hash($context, $tmp_name): void {
        if (is_array($tmp_name)) {
            ksort($tmp_name);
            foreach ($tmp_name as $nested_tmp_name) {
                $this->append_tmp_name_hash($context, $nested_tmp_name);
            }
            return;
        }

        if (!is_string($tmp_name) || $tmp_name === '' || !is_readable($tmp_name)) {
            return;
        }

        if (!@hash_update_file($context, $tmp_name)) {
            throw new RuntimeException('Cannot hash uploaded file.');
        }
    }
}
