<?php
/**
 * Base class for runtime appliers.
 *
 * A runtime applier takes a RuntimeManifest and writes the configuration
 * files needed to run the imported site on a specific server platform.
 * Every applier generates a bootstrap.php (constants, server vars, and
 * interceptor requires) — the difference is in how that bootstrap gets
 * loaded: .user.ini for FPM-based servers, router.php for the PHP
 * built-in server, Caddyfile directives for FrankenPHP, etc.
 */
abstract class RuntimeApplier
{
    /**
     * Apply a manifest to the target docroot.
     *
     * @param RuntimeManifest $manifest  The manifest to apply.
     * @param string          $docroot   Absolute path to the site docroot.
     * @param string          $state_dir Absolute path to the state directory
     *                                   (where runtime/ scripts and manifest live).
     * @return string[] Human-readable summary lines (printed to the user).
     */
    abstract public function apply(RuntimeManifest $manifest, string $docroot, string $state_dir): array;

    /**
     * Pick the right applier for a runtime name.
     *
     * @param string $runtime "nginx-fpm" or "php-builtin".
     * @return self
     */
    public static function for_runtime(string $runtime): self
    {
        switch ($runtime) {
            case 'nginx-fpm':
                return new NginxFpmApplier();
            case 'php-builtin':
                return new PhpBuiltinApplier();
            default:
                throw new InvalidArgumentException(
                    "Unknown runtime: {$runtime}. Valid runtimes: nginx-fpm, php-builtin"
                );
        }
    }

    /**
     * Generate the bootstrap.php content that every applier uses.
     *
     * This is the common PHP file that sets constants, server vars, and
     * requires interceptor scripts. Each applier arranges for it to be
     * loaded before WordPress (via auto_prepend_file, router.php, etc.).
     */
    protected function generate_bootstrap(RuntimeManifest $manifest, string $docroot, string $state_dir): string
    {
        $lines = [];
        $lines[] = '<?php';
        $lines[] = '/**';
        $lines[] = ' * Runtime bootstrap — generated by apply-runtime.';
        $lines[] = ' * Source host: ' . $manifest->source;
        $lines[] = ' *';
        $lines[] = ' * This file sets PHP constants, server variables, and loads';
        $lines[] = ' * request interceptor scripts that the imported site needs.';
        $lines[] = ' * It is loaded before WordPress boots via auto_prepend_file,';
        $lines[] = ' * a router script, or an equivalent mechanism.';
        $lines[] = ' */';
        $lines[] = '';

        // Constants
        if (!empty($manifest->constants)) {
            $lines[] = '// PHP constants from the source host environment.';
            foreach ($manifest->constants as $name => $value) {
                $resolved = $this->resolve_placeholders($value, $docroot);
                $escaped = addslashes($resolved);
                $lines[] = "if (!defined('{$name}')) {";
                $lines[] = "    define('{$name}', '{$escaped}');";
                $lines[] = "}";
            }
            $lines[] = '';
        }

        // Server variables
        if (!empty($manifest->server_vars)) {
            $lines[] = '// $_SERVER entries from the source host environment.';
            foreach ($manifest->server_vars as $name => $value) {
                $resolved = $this->resolve_placeholders($value, $docroot);
                $escaped = addslashes($resolved);
                $lines[] = "\$_SERVER['{$name}'] = '{$escaped}';";
            }
            $lines[] = '';
        }

        // Request interceptors
        if (!empty($manifest->request_interceptors)) {
            $lines[] = '// Request interceptors — run before WordPress boots.';
            foreach ($manifest->request_interceptors as $interceptor) {
                $script_path = $state_dir . '/' . $interceptor['script'];
                $escaped = addslashes($script_path);
                $lines[] = "require '{$escaped}';";
            }
            $lines[] = '';
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * Replace {docroot} placeholders with the actual docroot path.
     */
    protected function resolve_placeholders(string $value, string $docroot): string
    {
        return str_replace('{docroot}', rtrim($docroot, '/'), $value);
    }

    /**
     * Write a file and return the path for reporting.
     */
    protected function write_file(string $path, string $content): void
    {
        $dir = dirname($path);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }
        file_put_contents($path, $content);
    }
}
