<?php
/**
 * Runtime applier for nginx + PHP-FPM (also works with Apache + PHP-FPM).
 *
 * PHP-FPM reads .user.ini files from the document root on every request
 * (cached for user_ini.cache_ttl seconds, default 300). This applier writes:
 *
 * 1. {state_dir}/bootstrap.php — constants, server vars, and error handlers
 * 2. {docroot}/.user.ini       — auto_prepend_file pointing to the bootstrap,
 *                                 plus any INI directives from the manifest
 *
 * Error handlers (like thumbnail generation) are inlined into the bootstrap
 * since auto_prepend_file runs before every PHP request — exactly the hook
 * point we need.
 */
class NginxFpmApplier extends RuntimeApplier
{
    public function apply(RuntimeManifest $manifest, string $docroot, string $state_dir): array
    {
        $summary = [];

        // 1. Write bootstrap.php (constants + server vars + error handlers)
        $bootstrap_path = $state_dir . '/bootstrap.php';
        $bootstrap = $this->generate_bootstrap($manifest, $docroot);

        // Append error handlers to the bootstrap — they run on every request
        // via auto_prepend_file, before WordPress boots.
        if ($this->has_thumbnail_handler($manifest)) {
            $bootstrap .= $this->generate_thumbnail_handler() . "\n";
        }

        $this->write_file($bootstrap_path, $bootstrap);
        $summary[] = "Wrote {$bootstrap_path}";

        // 2. Write .user.ini in the docroot
        $user_ini_path = $docroot . '/.user.ini';
        $user_ini = $this->generate_user_ini($manifest, $bootstrap_path);
        $this->write_file($user_ini_path, $user_ini);
        $summary[] = "Wrote {$user_ini_path}";

        $summary[] = '';
        $summary[] = 'The .user.ini file will be picked up automatically by PHP-FPM.';
        $summary[] = 'It may take up to 5 minutes (user_ini.cache_ttl) to take effect.';
        $summary[] = '';
        $summary[] = 'This works with both nginx + PHP-FPM and Apache + PHP-FPM.';

        return $summary;
    }

    private function generate_user_ini(RuntimeManifest $manifest, string $bootstrap_path): string
    {
        $lines = [];
        $lines[] = '; Runtime configuration — generated by apply-runtime.';
        $lines[] = '; Source host: ' . $manifest->source;
        $lines[] = '';

        // auto_prepend_file loads the bootstrap before every PHP request.
        $lines[] = 'auto_prepend_file = ' . $bootstrap_path;
        $lines[] = '';

        // INI directives from the source host.
        if (!empty($manifest->php_ini)) {
            $lines[] = '; PHP INI directives from the source host.';
            foreach ($manifest->php_ini as $key => $value) {
                $lines[] = "{$key} = {$value}";
            }
            $lines[] = '';
        }

        return implode("\n", $lines) . "\n";
    }
}
