<?php
/**
 * Runtime applier for PHP's built-in development server.
 *
 * Writes:
 * 1. {output_dir}/runtime.php — constants, server vars, route handlers,
 *                                and CLI-server routing logic
 * 2. {output_dir}/start.sh    — shell script with the exact php -S command
 *
 * runtime.php serves double duty: it's both the router script (passed to
 * php -S) and the auto_prepend_file (via -d). First execution as the
 * router runs all three layers. When the router returns false for a .php
 * file, php-S runs that file and auto_prepend_file fires again — but
 * constants are guarded, route handlers are idempotent, and the __ROUTED
 * guard prevents re-entering the routing block.
 *
 * The developer just runs: bash {output_dir}/start.sh
 */
class PhpBuiltinApplier extends RuntimeApplier
{
    public function apply(RuntimeManifest $manifest, string $docroot, string $output_dir, array $options = []): array
    {
        $host = $options['host'] ?? 'localhost';
        $port = (int) ($options['port'] ?? 8881);

        $summary = [];

        // 1. Write runtime.php (all three layers)
        $runtime_path = $output_dir . '/runtime.php';
        $runtime = $this->generate_runtime_php($manifest, $docroot);
        $this->write_file($runtime_path, $runtime);
        $summary[] = "Wrote {$runtime_path}";

        // 2. Write start.sh
        $start_path = $output_dir . '/start.sh';
        $start_script = $this->generate_start_script($manifest, $docroot, $runtime_path, $host, $port);
        $this->write_file($start_path, $start_script);
        chmod($start_path, 0755);
        $summary[] = "Wrote {$start_path}";

        $summary[] = '';
        $summary[] = 'Start the server:';
        $summary[] = "  bash {$start_path}";
        $summary[] = '';
        $summary[] = "Then open http://{$host}:{$port} in your browser.";

        return $summary;
    }

    /**
     * Generate a shell script that starts the built-in server.
     * runtime.php is used as both the router script and auto_prepend_file.
     */
    private function generate_start_script(
        RuntimeManifest $manifest,
        string $docroot,
        string $runtime_path,
        string $host,
        int $port
    ): string {
        $lines = [];
        $lines[] = '#!/usr/bin/env bash';
        $lines[] = '# Start the PHP built-in server for the imported site.';
        $lines[] = '# Generated by apply-runtime — do not edit.';
        $lines[] = '#';
        $lines[] = '# Source host: ' . $manifest->source;
        $lines[] = '';
        $lines[] = 'set -euo pipefail';
        $lines[] = '';

        $php_args = [];
        $php_args[] = 'php';

        // runtime.php is auto_prepend_file so constants are defined for
        // every PHP file php-S executes (WordPress, plugins, etc.), not
        // just the router entry point.
        $php_args[] = '-d auto_prepend_file=' . escapeshellarg($runtime_path);

        foreach ($manifest->php_ini as $key => $value) {
            $php_args[] = "-d {$key}={$value}";
        }

        $php_args[] = '-S ' . $host . ':' . $port;
        $php_args[] = '-t ' . escapeshellarg($docroot);

        // Same file as the router script — layer 3 (cli-server routing)
        // handles static files and WordPress pretty-permalink fallback.
        $php_args[] = escapeshellarg($runtime_path);

        $lines[] = 'echo "Starting PHP built-in server..."';
        $lines[] = 'echo "  http://' . $host . ':' . $port . '"';
        $lines[] = 'echo ""';
        $lines[] = '';
        $lines[] = implode(" \\\n    ", $php_args);
        $lines[] = '';

        return implode("\n", $lines);
    }
}
