<?php
/**
 * Runtime applier for PHP's built-in development server.
 *
 * PHP's built-in server (php -S) doesn't read .user.ini files, but it
 * supports a router script that runs before every request. This applier writes:
 *
 * 1. {state_dir}/bootstrap.php — constants, server vars, interceptors
 * 2. {docroot}/router.php      — router that loads the bootstrap, serves
 *                                 static files directly, and falls through
 *                                 to WordPress for dynamic requests
 * 3. {state_dir}/start.sh      — shell script with the exact php -S command
 *
 * The developer just runs: bash {state_dir}/start.sh
 */
class PhpBuiltinApplier extends RuntimeApplier
{
    private string $host = 'localhost';
    private int $port = 8881;

    public function apply(RuntimeManifest $manifest, string $docroot, string $state_dir): array
    {
        $summary = [];

        // 1. Write bootstrap.php
        $bootstrap_path = $state_dir . '/bootstrap.php';
        $bootstrap = $this->generate_bootstrap($manifest, $docroot, $state_dir);
        $this->write_file($bootstrap_path, $bootstrap);
        $summary[] = "Wrote {$bootstrap_path}";

        // 2. Write router.php in the docroot
        $router_path = $docroot . '/router.php';
        $router = $this->generate_router($bootstrap_path);
        $this->write_file($router_path, $router);
        $summary[] = "Wrote {$router_path}";

        // 3. Write start.sh
        $start_path = $state_dir . '/start.sh';
        $start_script = $this->generate_start_script($manifest, $docroot, $router_path);
        $this->write_file($start_path, $start_script);
        chmod($start_path, 0755);
        $summary[] = "Wrote {$start_path}";

        $summary[] = '';
        $summary[] = 'Start the server:';
        $summary[] = "  bash {$start_path}";
        $summary[] = '';
        $summary[] = "Then open http://{$this->host}:{$this->port} in your browser.";

        return $summary;
    }

    /**
     * The router script runs on every request. It loads the bootstrap (which
     * sets constants and runs interceptors that may exit), then serves static
     * files directly or falls through to WordPress.
     */
    private function generate_router(string $bootstrap_path): string
    {
        $escaped_bootstrap = addslashes($bootstrap_path);

        return <<<'PHP'
<?php
/**
 * Router script for PHP's built-in development server.
 * Generated by apply-runtime — do not edit.
 *
 * Loads the runtime bootstrap (constants, interceptors), then either
 * serves static files directly or routes dynamic requests to WordPress.
 */

// Load the runtime bootstrap — this defines constants, sets server vars,
// and runs request interceptors (like the thumbnail generator) that may
// exit() before WordPress ever boots.
require '
PHP
        . $escaped_bootstrap . "';\n\n"
        . <<<'PHP'
$uri = $_SERVER['REQUEST_URI'] ?? '/';
$path = parse_url($uri, PHP_URL_PATH);

// Map the URL to a file in the docroot.
$file = $_SERVER['DOCUMENT_ROOT'] . $path;

// Serve existing static files directly (CSS, JS, images, etc.).
// Return false to let PHP's built-in server use its default static handler.
if ($path !== '/' && file_exists($file) && is_file($file)) {
    // PHP files need to be executed, not served as static.
    if (preg_match('/\.php$/', $file)) {
        return false;
    }
    return false;
}

// For directory requests, look for index.php or index.html.
if (is_dir($file)) {
    if (file_exists($file . '/index.php')) {
        $_SERVER['SCRIPT_NAME'] = $path . '/index.php';
        require $file . '/index.php';
        return;
    }
    if (file_exists($file . '/index.html')) {
        return false;
    }
}

// Everything else goes to WordPress via index.php (pretty permalinks).
$_SERVER['SCRIPT_NAME'] = '/index.php';
require $_SERVER['DOCUMENT_ROOT'] . '/index.php';
PHP
        . "\n";
    }

    /**
     * Generate a shell script that starts the built-in server with the right
     * arguments, including any INI overrides from the manifest.
     */
    private function generate_start_script(RuntimeManifest $manifest, string $docroot, string $router_path): string
    {
        $lines = [];
        $lines[] = '#!/usr/bin/env bash';
        $lines[] = '# Start the PHP built-in server for the imported site.';
        $lines[] = '# Generated by apply-runtime — do not edit.';
        $lines[] = '#';
        $lines[] = '# Source host: ' . $manifest->source;
        $lines[] = '';
        $lines[] = 'set -euo pipefail';
        $lines[] = '';

        // Build the php command with INI overrides
        $php_args = [];
        $php_args[] = 'php';

        foreach ($manifest->php_ini as $key => $value) {
            $php_args[] = "-d {$key}={$value}";
        }

        $php_args[] = '-S ' . $this->host . ':' . $this->port;
        $php_args[] = '-t ' . escapeshellarg($docroot);
        $php_args[] = escapeshellarg($router_path);

        $lines[] = 'echo "Starting PHP built-in server..."';
        $lines[] = 'echo "  http://' . $this->host . ':' . $this->port . '"';
        $lines[] = 'echo ""';
        $lines[] = '';
        $lines[] = implode(" \\\n    ", $php_args);
        $lines[] = '';

        return implode("\n", $lines);
    }
}
