<?php
/**
 * Base class for runtime appliers.
 *
 * A runtime applier takes a RuntimeManifest and writes the configuration
 * files needed to run the imported site on a specific server platform.
 * Every applier generates a bootstrap.php (constants and server vars) —
 * the difference is in how that bootstrap gets loaded and how error
 * handlers are implemented.
 */
abstract class RuntimeApplier
{
    /**
     * Apply a manifest to the target docroot.
     *
     * @param RuntimeManifest $manifest  The manifest to apply.
     * @param string          $docroot   Absolute path to the site docroot.
     * @param string          $state_dir Absolute path to the state directory.
     * @return string[] Human-readable summary lines (printed to the user).
     */
    abstract public function apply(RuntimeManifest $manifest, string $docroot, string $state_dir): array;

    /**
     * Pick the right applier for a runtime name.
     *
     * @param string $runtime "nginx-fpm" or "php-builtin".
     * @return self
     */
    public static function for_runtime(string $runtime): self
    {
        switch ($runtime) {
            case 'nginx-fpm':
                return new NginxFpmApplier();
            case 'php-builtin':
                return new PhpBuiltinApplier();
            default:
                throw new InvalidArgumentException(
                    "Unknown runtime: {$runtime}. Valid runtimes: nginx-fpm, php-builtin"
                );
        }
    }

    /**
     * Generate the bootstrap.php that sets constants and server vars.
     *
     * This does NOT include error handlers — each applier implements
     * those in a way that's native to its platform (router logic for
     * php-builtin, a separate PHP script for nginx, etc.).
     */
    protected function generate_bootstrap(RuntimeManifest $manifest, string $docroot): string
    {
        $lines = [];
        $lines[] = '<?php';
        $lines[] = '/**';
        $lines[] = ' * Runtime bootstrap — generated by apply-runtime.';
        $lines[] = ' * Source host: ' . $manifest->source;
        $lines[] = ' *';
        $lines[] = ' * This file sets PHP constants and server variables that the';
        $lines[] = ' * imported site needs. It is loaded before WordPress boots via';
        $lines[] = ' * auto_prepend_file, a router script, or an equivalent mechanism.';
        $lines[] = ' */';
        $lines[] = '';

        // Constants
        if (!empty($manifest->constants)) {
            $lines[] = '// PHP constants from the source host environment.';
            foreach ($manifest->constants as $name => $value) {
                $resolved = $this->resolve_placeholders($value, $docroot);
                $escaped = addslashes($resolved);
                $lines[] = "if (!defined('{$name}')) {";
                $lines[] = "    define('{$name}', '{$escaped}');";
                $lines[] = "}";
            }
            $lines[] = '';
        }

        // Server variables
        if (!empty($manifest->server_vars)) {
            $lines[] = '// $_SERVER entries from the source host environment.';
            foreach ($manifest->server_vars as $name => $value) {
                $resolved = $this->resolve_placeholders($value, $docroot);
                $escaped = addslashes($resolved);
                $lines[] = "\$_SERVER['{$name}'] = '{$escaped}';";
            }
            $lines[] = '';
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * Generate PHP code for a thumbnail-generator error handler.
     *
     * This is the implementation that target runtimes embed wherever
     * they handle 404s. It generates resized images on-the-fly from
     * originals using GD, caches them on disk, and serves them.
     *
     * The returned code is a self-contained IIFE that:
     * - Checks $_SERVER['REQUEST_URI'] against the path pattern
     * - Requires WP_CONTENT_DIR to be defined (by the bootstrap)
     * - Calls exit() after serving the generated thumbnail
     * - Returns silently if the request doesn't match
     */
    protected function generate_thumbnail_handler(): string
    {
        return <<<'PHP'
/**
 * On-the-fly thumbnail generation for WordPress upload images.
 *
 * WordPress stores references to sized variants like image-768x768.jpeg in
 * post meta, but the exported site only has the original full-size file.
 * This intercepts requests for missing thumbnails inside /wp-content/uploads/,
 * generates a properly resized copy from the original using GD, caches it on
 * disk so subsequent requests are served directly, and exits before WordPress
 * boots — keeping it fast.
 */
(function() {
	if (!defined('WP_CONTENT_DIR')) return;

	$uri = $_SERVER['REQUEST_URI'] ?? '';
	$path = parse_url($uri, PHP_URL_PATH);
	if (!$path) return;

	// Only handle requests inside /wp-content/uploads/
	if (strpos($path, '/wp-content/uploads/') === false) return;

	// Only handle filenames with a -WxH thumbnail suffix
	if (!preg_match('/-(\d+)x(\d+)(\.\w+)$/', $path, $m)) return;

	$max_width  = (int) $m[1];
	$max_height = (int) $m[2];
	$ext        = strtolower($m[3]);

	// Map the URL path to a filesystem path relative to WP_CONTENT_DIR.
	$relative   = preg_replace('#^.*/wp-content/#', '', $path);
	$thumb_path = WP_CONTENT_DIR . '/' . $relative;

	// If the thumbnail already exists on disk, let the server handle it
	if (file_exists($thumb_path)) return;

	// Derive the original (unsized) file path
	$original_path = preg_replace('/-\d+x\d+(\.\w+)$/', '$1', $thumb_path);
	if (!file_exists($original_path)) return;

	// Load the original image with GD
	$src = null;
	switch ($ext) {
		case '.jpg':
		case '.jpeg':
			$src = @imagecreatefromjpeg($original_path);
			break;
		case '.png':
			$src = @imagecreatefrompng($original_path);
			break;
		case '.gif':
			$src = @imagecreatefromgif($original_path);
			break;
		case '.webp':
			if (function_exists('imagecreatefromwebp')) {
				$src = @imagecreatefromwebp($original_path);
			}
			break;
	}
	if (!$src) return;

	// Compute the scaled dimensions (fit inside max_width x max_height,
	// never enlarge beyond the original)
	$orig_w = imagesx($src);
	$orig_h = imagesy($src);
	$scale  = min($max_width / $orig_w, $max_height / $orig_h, 1.0);
	$new_w  = (int) round($orig_w * $scale);
	$new_h  = (int) round($orig_h * $scale);

	$dst = imagecreatetruecolor($new_w, $new_h);

	// Preserve transparency for PNG and GIF
	if ($ext === '.png') {
		imagealphablending($dst, false);
		imagesavealpha($dst, true);
	} elseif ($ext === '.gif') {
		$transparent = imagecolortransparent($src);
		if ($transparent >= 0) {
			$color = imagecolorsforindex($src, $transparent);
			$new_transparent = imagecolorallocate($dst, $color['red'], $color['green'], $color['blue']);
			imagefill($dst, 0, 0, $new_transparent);
			imagecolortransparent($dst, $new_transparent);
		}
	}

	imagecopyresampled($dst, $src, 0, 0, 0, 0, $new_w, $new_h, $orig_w, $orig_h);

	// Cache the thumbnail to disk so future requests skip this code path
	$thumb_dir = dirname($thumb_path);
	if (!is_dir($thumb_dir)) {
		@mkdir($thumb_dir, 0755, true);
	}

	$content_type = 'application/octet-stream';
	switch ($ext) {
		case '.jpg':
		case '.jpeg':
			imagejpeg($dst, $thumb_path, 82);
			$content_type = 'image/jpeg';
			break;
		case '.png':
			imagepng($dst, $thumb_path);
			$content_type = 'image/png';
			break;
		case '.gif':
			imagegif($dst, $thumb_path);
			$content_type = 'image/gif';
			break;
		case '.webp':
			imagewebp($dst, $thumb_path, 82);
			$content_type = 'image/webp';
			break;
	}

	imagedestroy($src);
	imagedestroy($dst);

	// Serve the freshly generated thumbnail and stop
	header('Content-Type: ' . $content_type);
	header('Content-Length: ' . filesize($thumb_path));
	readfile($thumb_path);
	exit;
})();
PHP;
    }

    /**
     * Check if the manifest declares a thumbnail-generator error handler.
     */
    protected function has_thumbnail_handler(RuntimeManifest $manifest): bool
    {
        foreach ($manifest->error_handlers as $handler) {
            if (($handler['type'] ?? '') === 'thumbnail-generator') {
                return true;
            }
        }
        return false;
    }

    /**
     * Replace {docroot} placeholders with the actual docroot path.
     */
    protected function resolve_placeholders(string $value, string $docroot): string
    {
        return str_replace('{docroot}', rtrim($docroot, '/'), $value);
    }

    /**
     * Write a file and return the path for reporting.
     */
    protected function write_file(string $path, string $content): void
    {
        $dir = dirname($path);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }
        file_put_contents($path, $content);
    }
}
