<?php
/**
 * Base class for runtime appliers.
 *
 * A runtime applier takes a RuntimeManifest and writes the configuration
 * files needed to run the imported site on a specific server platform.
 *
 * Every applier shares a single runtime.php file that works across all
 * platforms. It has three layers:
 *
 * 1. Constants + server vars (guarded by if-not-defined, safe to re-run)
 * 2. Route handlers (check URI / file_exists, idempotent per request)
 * 3. CLI-server routing (only runs under php -S, skipped under FPM)
 *
 * For nginx/FPM: auto_prepend_file = runtime.php. Layers 1-2 run, layer 3
 * is skipped. Nginx serves static files directly.
 *
 * For php-builtin: runtime.php is the router script. PHP files are
 * require'd by the router so they execute in the same scope where
 * constants are already defined. Only static non-PHP files use
 * return false to let php-S serve them directly.
 */
abstract class RuntimeApplier
{
    /**
     * Apply a manifest to the target docroot.
     *
     * @param RuntimeManifest $manifest   The manifest to apply.
     * @param string          $docroot    Absolute path to the site docroot.
     * @param string          $output_dir Absolute path to the output directory.
     * @param array           $options    Runtime-specific options (e.g. host, port).
     * @return string[] Human-readable summary lines (printed to the user).
     */
    abstract public function apply(RuntimeManifest $manifest, string $docroot, string $output_dir, array $options = []): array;

    /**
     * Pick the right applier for a runtime name.
     *
     * @param string $runtime "nginx-fpm" or "php-builtin".
     * @return self
     */
    public static function for_runtime(string $runtime): self
    {
        switch ($runtime) {
            case 'nginx-fpm':
                return new NginxFpmApplier();
            case 'php-builtin':
                return new PhpBuiltinApplier();
            default:
                throw new InvalidArgumentException(
                    "Unknown runtime: {$runtime}. Valid runtimes: nginx-fpm, php-builtin"
                );
        }
    }

    /**
     * Generate runtime.php — the single PHP file that works across all
     * server platforms.
     *
     * Layer 1: Constants and server vars (always runs, guarded)
     * Layer 2: Route handlers (always runs, idempotent)
     * Layer 3: CLI-server routing (only under php -S)
     *
     * @param RuntimeManifest $manifest
     * @param string          $docroot  Absolute path to the effective docroot.
     * @param array           $options  Must include 'wordpress_index' — absolute
     *                                  path to WordPress's index.php (may differ
     *                                  from docroot on hosts like WPCloud).
     */
    protected function generate_runtime_php(RuntimeManifest $manifest, string $docroot, array $options = []): string
    {
        $wp_index = $options['wordpress_index'] ?? ($docroot . '/index.php');
        $escaped_wp_index = addslashes($wp_index);

        $lines = [];
        $lines[] = '<?php';
        $lines[] = '/**';
        $lines[] = ' * Runtime configuration — generated by apply-runtime.';
        $lines[] = ' * Source host: ' . $manifest->source;
        $lines[] = ' *';
        $lines[] = ' * This file works as both an auto_prepend_file (for FPM-based servers)';
        $lines[] = ' * and a router script (for PHP\'s built-in server). Three layers:';
        $lines[] = ' *';
        $lines[] = ' * 1. Constants + server vars — guarded, safe to re-run';
        $lines[] = ' * 2. Route handlers — idempotent per request';
        $lines[] = ' * 3. CLI-server routing — only runs under php -S';
        $lines[] = ' */';
        $lines[] = '';

        // Layer 1: Constants
        if (!empty($manifest->constants)) {
            foreach ($manifest->constants as $name => $value) {
                $resolved = $this->resolve_placeholders($value, $docroot);
                $escaped = addslashes($resolved);
                $lines[] = "if (!defined('{$name}')) {";
                $lines[] = "    define('{$name}', '{$escaped}');";
                $lines[] = "}";
            }
            $lines[] = '';
        }

        // Layer 1: Server variables
        if (!empty($manifest->server_vars)) {
            foreach ($manifest->server_vars as $name => $value) {
                $resolved = $this->resolve_placeholders($value, $docroot);
                $escaped = addslashes($resolved);
                $lines[] = "\$_SERVER['{$name}'] = '{$escaped}';";
            }
            $lines[] = '';
        }

        // Layer 2: Route handlers
        $route_code = $this->generate_route_handler_code($manifest);
        if ($route_code !== '') {
            $lines[] = $route_code;
        }

        // Layer 3: CLI-server routing (php -S).
        // Under FPM/Apache, auto_prepend_file returns here and the actual
        // PHP file executes. Under php -S, this block handles static files
        // and WordPress pretty-permalink routing.
        $lines[] = "if (php_sapi_name() === 'cli-server' && !defined('__ROUTED')) {";
        $lines[] = "    define('__ROUTED', true);";
        $lines[] = '';
        $lines[] = '    $path = parse_url($_SERVER[\'REQUEST_URI\'] ?? \'/\', PHP_URL_PATH);';
        $lines[] = '';
        $lines[] = '    // Support PATH_INFO URLs like /file.php/extra/path.';
        $lines[] = '    // Walk the path segments to find the first .php file that exists,';
        $lines[] = '    // then split into SCRIPT_NAME and PATH_INFO.';
        $lines[] = '    $script_file = null;';
        $lines[] = '    $path_info = \'\';';
        $lines[] = '    if (preg_match(\'#\\.php(?=/|$)#\', $path)) {';
        $lines[] = '        $segments = explode(\'/\', $path);';
        $lines[] = '        $check = \'\';';
        $lines[] = '        foreach ($segments as $i => $seg) {';
        $lines[] = '            $check .= ($i > 0 ? \'/\' : \'\') . $seg;';
        $lines[] = '            $candidate = $_SERVER[\'DOCUMENT_ROOT\'] . $check;';
        $lines[] = '            if (is_file($candidate) && preg_match(\'/\\.php$/\', $check)) {';
        $lines[] = '                $script_file = $candidate;';
        $lines[] = '                $path_info = substr($path, strlen($check));';
        $lines[] = '                $_SERVER[\'SCRIPT_NAME\'] = $check;';
        $lines[] = '                $_SERVER[\'PATH_INFO\'] = $path_info ?: null;';
        $lines[] = '                break;';
        $lines[] = '            }';
        $lines[] = '        }';
        $lines[] = '    }';
        $lines[] = '';
        $lines[] = '    if ($script_file) {';
        $lines[] = '        require $script_file;';
        $lines[] = '        return;';
        $lines[] = '    }';
        $lines[] = '';
        $lines[] = '    $file = $_SERVER[\'DOCUMENT_ROOT\'] . $path;';
        $lines[] = '';
        $lines[] = '    // Existing non-PHP files: let php -S serve them as static.';
        $lines[] = '    if ($path !== \'/\' && file_exists($file) && is_file($file)) {';
        $lines[] = '        return false;';
        $lines[] = '    }';
        $lines[] = '';
        $lines[] = '    // Directory requests: look for index.php or index.html.';
        $lines[] = '    if (is_dir($file)) {';
        $lines[] = '        if (file_exists($file . \'/index.php\')) {';
        $lines[] = '            $_SERVER[\'SCRIPT_NAME\'] = $path . \'/index.php\';';
        $lines[] = '            require $file . \'/index.php\';';
        $lines[] = '            return;';
        $lines[] = '        }';
        $lines[] = '        if (file_exists($file . \'/index.html\')) {';
        $lines[] = '            return false;';
        $lines[] = '        }';
        $lines[] = '    }';
        $lines[] = '';
        $lines[] = '    // Everything else: WordPress pretty permalinks via index.php.';
        $lines[] = '    // WordPress index.php may live outside the document root (e.g.';
        $lines[] = '    // WPCloud where ABSPATH differs from the document root).';
        $lines[] = '    $_SERVER[\'SCRIPT_NAME\'] = \'/index.php\';';
        $lines[] = "    require '{$escaped_wp_index}';";
        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * Generate PHP code for all route handlers declared in the manifest.
     *
     * The handler name maps 1:1 to a function in route-handlers/:
     * "wpcloud-thumbnail-generator" → wpcloud_thumbnail_generator_code().
     *
     * Returns empty string if no routes are declared. Unknown handler
     * names are silently skipped — they may be handled by a future
     * applier version.
     */
    protected function generate_route_handler_code(RuntimeManifest $manifest): string
    {
        $code = '';
        foreach ($manifest->routes as $route) {
            $handler = $route['handler'] ?? '';
            switch ($handler) {
                case 'wpcloud-thumbnail-generator':
                    $code .= wpcloud_thumbnail_generator_code() . "\n";
                    break;
            }
        }
        return $code;
    }

    /**
     * Replace {docroot} placeholders with the actual docroot path.
     */
    protected function resolve_placeholders(string $value, string $docroot): string
    {
        return str_replace('{docroot}', rtrim($docroot, '/'), $value);
    }

    /**
     * Write a file and return the path for reporting.
     */
    protected function write_file(string $path, string $content): void
    {
        $dir = dirname($path);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }
        file_put_contents($path, $content);
    }
}
