<?php
/**
 * Runtime applier for PHP's built-in development server.
 *
 * PHP's built-in server (php -S) doesn't read .user.ini files, but it
 * supports a router script and -d flags for INI overrides. This applier:
 *
 * 1. {output_dir}/bootstrap.php — constants, server vars (loaded via
 *                                  auto_prepend_file so they're defined
 *                                  for both the router and WordPress)
 * 2. {output_dir}/router.php    — error handlers, static file routing,
 *                                  WordPress fallback
 * 3. {output_dir}/start.sh      — shell script with the exact php -S command
 *
 * The developer just runs: bash {output_dir}/start.sh
 */
class PhpBuiltinApplier extends RuntimeApplier
{
    private string $host = 'localhost';
    private int $port = 8881;

    public function apply(RuntimeManifest $manifest, string $docroot, string $output_dir): array
    {
        $summary = [];

        // 1. Write bootstrap.php (constants + server vars)
        $bootstrap_path = $output_dir . '/bootstrap.php';
        $bootstrap = $this->generate_bootstrap($manifest, $docroot);
        $this->write_file($bootstrap_path, $bootstrap);
        $summary[] = "Wrote {$bootstrap_path}";

        // 2. Write router.php in the output directory (not the docroot —
        //    we don't want to pollute the site's files)
        $router_path = $output_dir . '/router.php';
        $router = $this->generate_router($manifest);
        $this->write_file($router_path, $router);
        $summary[] = "Wrote {$router_path}";

        // 3. Write start.sh
        $start_path = $output_dir . '/start.sh';
        $start_script = $this->generate_start_script($manifest, $docroot, $bootstrap_path, $router_path);
        $this->write_file($start_path, $start_script);
        chmod($start_path, 0755);
        $summary[] = "Wrote {$start_path}";

        $summary[] = '';
        $summary[] = 'Start the server:';
        $summary[] = "  bash {$start_path}";
        $summary[] = '';
        $summary[] = "Then open http://{$this->host}:{$this->port} in your browser.";

        return $summary;
    }

    /**
     * The router script runs on every request. Constants and server vars
     * are already set by auto_prepend_file (bootstrap.php), so the router
     * only needs to handle error handlers, static files, and WordPress
     * routing.
     */
    private function generate_router(RuntimeManifest $manifest): string
    {
        $parts = [];
        $parts[] = '<?php';
        $parts[] = '/**';
        $parts[] = ' * Router script for PHP\'s built-in development server.';
        $parts[] = ' * Generated by apply-runtime — do not edit.';
        $parts[] = ' *';
        $parts[] = ' * Constants and server vars are set by auto_prepend_file';
        $parts[] = ' * (bootstrap.php). This router handles route handlers,';
        $parts[] = ' * static file serving, and WordPress routing.';
        $parts[] = ' */';
        $parts[] = '';

        // Inline route handlers (e.g. WP Cloud thumbnail generation).
        // These check the request URI and may exit before WordPress
        // routing, so they must come first.
        $route_handler_code = $this->generate_route_handler_code($manifest);
        if ($route_handler_code !== '') {
            $parts[] = $route_handler_code;
        }

        $parts[] = '$uri = $_SERVER[\'REQUEST_URI\'] ?? \'/\';';
        $parts[] = '$path = parse_url($uri, PHP_URL_PATH);';
        $parts[] = '';
        $parts[] = '// Map the URL to a file in the docroot.';
        $parts[] = '$file = $_SERVER[\'DOCUMENT_ROOT\'] . $path;';
        $parts[] = '';
        $parts[] = '// Serve existing static files directly (CSS, JS, images, etc.).';
        $parts[] = '// Return false to let PHP\'s built-in server use its default static handler.';
        $parts[] = 'if ($path !== \'/\' && file_exists($file) && is_file($file)) {';
        $parts[] = '    return false;';
        $parts[] = '}';
        $parts[] = '';
        $parts[] = '// For directory requests, look for index.php or index.html.';
        $parts[] = 'if (is_dir($file)) {';
        $parts[] = '    if (file_exists($file . \'/index.php\')) {';
        $parts[] = '        $_SERVER[\'SCRIPT_NAME\'] = $path . \'/index.php\';';
        $parts[] = '        require $file . \'/index.php\';';
        $parts[] = '        return;';
        $parts[] = '    }';
        $parts[] = '    if (file_exists($file . \'/index.html\')) {';
        $parts[] = '        return false;';
        $parts[] = '    }';
        $parts[] = '}';
        $parts[] = '';
        $parts[] = '// Everything else goes to WordPress via index.php (pretty permalinks).';
        $parts[] = '$_SERVER[\'SCRIPT_NAME\'] = \'/index.php\';';
        $parts[] = 'require $_SERVER[\'DOCUMENT_ROOT\'] . \'/index.php\';';

        return implode("\n", $parts) . "\n";
    }

    /**
     * Generate a shell script that starts the built-in server with the right
     * arguments. Uses -d auto_prepend_file to load the bootstrap so constants
     * are defined for both the router and any PHP files WordPress loads.
     */
    private function generate_start_script(
        RuntimeManifest $manifest,
        string $docroot,
        string $bootstrap_path,
        string $router_path
    ): string {
        $lines = [];
        $lines[] = '#!/usr/bin/env bash';
        $lines[] = '# Start the PHP built-in server for the imported site.';
        $lines[] = '# Generated by apply-runtime — do not edit.';
        $lines[] = '#';
        $lines[] = '# Source host: ' . $manifest->source;
        $lines[] = '';
        $lines[] = 'set -euo pipefail';
        $lines[] = '';

        // Build the php command with INI overrides
        $php_args = [];
        $php_args[] = 'php';

        // auto_prepend_file ensures constants and server vars are defined
        // for every PHP execution — the router, WordPress, and any other
        // PHP file the server runs.
        $php_args[] = '-d auto_prepend_file=' . escapeshellarg($bootstrap_path);

        foreach ($manifest->php_ini as $key => $value) {
            $php_args[] = "-d {$key}={$value}";
        }

        $php_args[] = '-S ' . $this->host . ':' . $this->port;
        $php_args[] = '-t ' . escapeshellarg($docroot);
        $php_args[] = escapeshellarg($router_path);

        $lines[] = 'echo "Starting PHP built-in server..."';
        $lines[] = 'echo "  http://' . $this->host . ':' . $this->port . '"';
        $lines[] = 'echo ""';
        $lines[] = '';
        $lines[] = implode(" \\\n    ", $php_args);
        $lines[] = '';

        return implode("\n", $lines);
    }
}
