<?php
/**
 * Runtime applier for nginx + PHP-FPM (also works with Apache + PHP-FPM).
 *
 * Writes:
 * 1. {output_dir}/runtime.php — constants, server vars, route handlers
 *                                (loaded via auto_prepend_file)
 * 2. {docroot}/.user.ini      — auto_prepend_file + INI directives
 * 3. {output_dir}/nginx.conf  — nginx server block for the imported site
 *
 * The nginx config serves static files directly (no PHP) and routes
 * everything else through PHP-FPM, which loads runtime.php via
 * auto_prepend_file before every PHP execution.
 */
class NginxFpmApplier extends RuntimeApplier
{
    public function apply(RuntimeManifest $manifest, string $docroot, string $output_dir, array $options = []): array
    {
        $host = $options['host'] ?? 'localhost';
        $port = (int) ($options['port'] ?? 80);

        $summary = [];

        // 1. Write runtime.php
        $runtime_path = $output_dir . '/runtime.php';
        $runtime = $this->generate_runtime_php($manifest, $docroot, $options);
        $this->write_file($runtime_path, $runtime);
        $summary[] = "Wrote {$runtime_path}";

        // 2. Write .user.ini in the docroot
        $user_ini_path = $docroot . '/.user.ini';
        $user_ini = $this->generate_user_ini($manifest, $runtime_path);
        $this->write_file($user_ini_path, $user_ini);
        $summary[] = "Wrote {$user_ini_path}";

        // 3. Write nginx.conf
        $nginx_conf_path = $output_dir . '/nginx.conf';
        $nginx_conf = $this->generate_nginx_conf($docroot, $host, $port);
        $this->write_file($nginx_conf_path, $nginx_conf);
        $summary[] = "Wrote {$nginx_conf_path}";

        $summary[] = '';
        $summary[] = 'To use with nginx:';
        $summary[] = "  Include {$nginx_conf_path} in your nginx configuration,";
        $summary[] = '  then reload: nginx -s reload';
        $summary[] = '';
        $summary[] = 'The .user.ini file will be picked up automatically by PHP-FPM.';
        $summary[] = 'It may take up to 5 minutes (user_ini.cache_ttl) to take effect.';

        return $summary;
    }

    private function generate_user_ini(RuntimeManifest $manifest, string $runtime_path): string
    {
        $lines = [];
        $lines[] = '; Runtime configuration — generated by apply-runtime.';
        $lines[] = '; Source host: ' . $manifest->source;
        $lines[] = '';
        $lines[] = 'auto_prepend_file = ' . $runtime_path;
        $lines[] = '';

        if (!empty($manifest->php_ini)) {
            $lines[] = '; PHP INI directives from the source host.';
            foreach ($manifest->php_ini as $key => $value) {
                $lines[] = "{$key} = {$value}";
            }
            $lines[] = '';
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * Generate an nginx server block that serves static files directly
     * and routes PHP requests through PHP-FPM. This is a starting point —
     * the developer may need to adjust the fastcgi_pass address to match
     * their PHP-FPM configuration.
     */
    private function generate_nginx_conf(string $docroot, string $host, int $port): string
    {
        $lines = [];
        $lines[] = '# Nginx configuration — generated by apply-runtime.';
        $lines[] = '# Adjust fastcgi_pass to match your PHP-FPM socket or address.';
        $lines[] = '';
        $lines[] = 'server {';
        $lines[] = "    listen {$port};";
        $lines[] = "    server_name {$host};";
        $lines[] = "    root {$docroot};";
        $lines[] = '    index index.php index.html;';
        $lines[] = '';
        $lines[] = '    # Static files served directly by nginx — no PHP involved.';
        $lines[] = '    location / {';
        $lines[] = '        try_files $uri $uri/ /index.php?$args;';
        $lines[] = '    }';
        $lines[] = '';
        $lines[] = '    # PHP requests go through PHP-FPM. The .user.ini in the docroot';
        $lines[] = '    # sets auto_prepend_file = runtime.php, which defines constants,';
        $lines[] = '    # server vars, and route handlers before WordPress boots.';
        $lines[] = '    location ~ \.php$ {';
        $lines[] = '        try_files $uri =404;';
        $lines[] = '        fastcgi_pass unix:/var/run/php-fpm.sock;';
        $lines[] = '        fastcgi_index index.php;';
        $lines[] = '        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;';
        $lines[] = '        include fastcgi_params;';
        $lines[] = '    }';
        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }
}
