<?php
/**
 * Base class for runtime appliers.
 *
 * A runtime applier takes a RuntimeManifest and writes the configuration
 * files needed to run the imported site on a specific server platform.
 * Every applier generates a bootstrap.php (constants and server vars) —
 * the difference is in how that bootstrap gets loaded and how routes
 * are implemented.
 */
abstract class RuntimeApplier
{
    /**
     * Apply a manifest to the target docroot.
     *
     * @param RuntimeManifest $manifest  The manifest to apply.
     * @param string          $docroot   Absolute path to the site docroot.
     * @param string          $output_dir Absolute path to the output directory.
     * @return string[] Human-readable summary lines (printed to the user).
     */
    abstract public function apply(RuntimeManifest $manifest, string $docroot, string $output_dir): array;

    /**
     * Pick the right applier for a runtime name.
     *
     * @param string $runtime "nginx-fpm" or "php-builtin".
     * @return self
     */
    public static function for_runtime(string $runtime): self
    {
        switch ($runtime) {
            case 'nginx-fpm':
                return new NginxFpmApplier();
            case 'php-builtin':
                return new PhpBuiltinApplier();
            default:
                throw new InvalidArgumentException(
                    "Unknown runtime: {$runtime}. Valid runtimes: nginx-fpm, php-builtin"
                );
        }
    }

    /**
     * Generate the bootstrap.php that sets constants and server vars.
     *
     * This does NOT include route handlers — each applier implements
     * those in a way that's native to its platform (router logic for
     * php-builtin, auto_prepend_file for nginx, etc.).
     */
    protected function generate_bootstrap(RuntimeManifest $manifest, string $docroot): string
    {
        $lines = [];
        $lines[] = '<?php';
        $lines[] = '/**';
        $lines[] = ' * Runtime bootstrap — generated by apply-runtime.';
        $lines[] = ' * Source host: ' . $manifest->source;
        $lines[] = ' *';
        $lines[] = ' * This file sets PHP constants and server variables that the';
        $lines[] = ' * imported site needs. It is loaded before WordPress boots via';
        $lines[] = ' * auto_prepend_file, a router script, or an equivalent mechanism.';
        $lines[] = ' */';
        $lines[] = '';

        // Constants
        if (!empty($manifest->constants)) {
            $lines[] = '// PHP constants from the source host environment.';
            foreach ($manifest->constants as $name => $value) {
                $resolved = $this->resolve_placeholders($value, $docroot);
                $escaped = addslashes($resolved);
                $lines[] = "if (!defined('{$name}')) {";
                $lines[] = "    define('{$name}', '{$escaped}');";
                $lines[] = "}";
            }
            $lines[] = '';
        }

        // Server variables
        if (!empty($manifest->server_vars)) {
            $lines[] = '// $_SERVER entries from the source host environment.';
            foreach ($manifest->server_vars as $name => $value) {
                $resolved = $this->resolve_placeholders($value, $docroot);
                $escaped = addslashes($resolved);
                $lines[] = "\$_SERVER['{$name}'] = '{$escaped}';";
            }
            $lines[] = '';
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * Generate PHP code for all route handlers declared in the manifest.
     *
     * The handler name maps 1:1 to a function in route-handlers/:
     * "wpcloud-thumbnail-generator" → wpcloud_thumbnail_generator_code().
     *
     * Returns empty string if no routes are declared. Unknown handler
     * names are silently skipped — they may be handled by a future
     * applier version.
     */
    protected function generate_route_handler_code(RuntimeManifest $manifest): string
    {
        $code = '';
        foreach ($manifest->routes as $route) {
            $handler = $route['handler'] ?? '';
            switch ($handler) {
                case 'wpcloud-thumbnail-generator':
                    $code .= wpcloud_thumbnail_generator_code() . "\n";
                    break;
            }
        }
        return $code;
    }

    /**
     * Replace {docroot} placeholders with the actual docroot path.
     */
    protected function resolve_placeholders(string $value, string $docroot): string
    {
        return str_replace('{docroot}', rtrim($docroot, '/'), $value);
    }

    /**
     * Write a file and return the path for reporting.
     */
    protected function write_file(string $path, string $content): void
    {
        $dir = dirname($path);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }
        file_put_contents($path, $content);
    }
}
