<?php
/**
 * Shared helpers for generating runtime.php content.
 *
 * These functions produce PHP code strings that runtime appliers embed
 * in the generated runtime.php file. They're standalone functions rather
 * than methods on the RuntimeApplier interface because they're shared
 * implementation details, not part of the contract.
 */

/**
 * Generate the base runtime.php content: constants, server vars, and
 * route handlers.
 *
 * Appliers may append platform-specific code to the result (e.g. the
 * php-builtin applier adds CLI-server routing).
 */
function generate_runtime_php(RuntimeManifest $manifest, string $docroot): string
{
    $lines = [];
    $lines[] = '<?php';
    $lines[] = '/**';
    $lines[] = ' * Runtime configuration — generated by apply-runtime.';
    $lines[] = ' * Source host: ' . $manifest->source;
    $lines[] = ' */';
    $lines[] = '';

    // Constants
    if (!empty($manifest->constants)) {
        foreach ($manifest->constants as $name => $value) {
            $resolved = resolve_runtime_placeholders($value, $docroot);
            $escaped = addslashes($resolved);
            $lines[] = "if (!defined('{$name}')) {";
            $lines[] = "    define('{$name}', '{$escaped}');";
            $lines[] = "}";
        }
        $lines[] = '';
    }

    // Server variables
    if (!empty($manifest->server_vars)) {
        foreach ($manifest->server_vars as $name => $value) {
            $resolved = resolve_runtime_placeholders($value, $docroot);
            $escaped = addslashes($resolved);
            $lines[] = "\$_SERVER['{$name}'] = '{$escaped}';";
        }
        $lines[] = '';
    }

    // Route handlers
    $route_code = generate_route_handler_code($manifest);
    if ($route_code !== '') {
        $lines[] = $route_code;
    }

    return implode("\n", $lines);
}

/**
 * Generate PHP code for all route handlers declared in the manifest.
 *
 * The handler name maps 1:1 to a function in route-handlers/:
 * "wpcloud-thumbnail-generator" → wpcloud_thumbnail_generator_code().
 *
 * Returns empty string if no routes are declared.
 */
function generate_route_handler_code(RuntimeManifest $manifest): string
{
    $code = '';
    foreach ($manifest->routes as $route) {
        $handler = $route['handler'] ?? '';
        switch ($handler) {
            case 'wpcloud-thumbnail-generator':
                $code .= wpcloud_thumbnail_generator_code() . "\n";
                break;
        }
    }
    return $code;
}

/**
 * Replace {docroot} placeholders with the actual docroot path.
 */
function resolve_runtime_placeholders(string $value, string $docroot): string
{
    return str_replace('{docroot}', rtrim($docroot, '/'), $value);
}

/**
 * Write a file, creating parent directories as needed.
 */
function write_runtime_file(string $path, string $content): void
{
    $dir = dirname($path);
    if (!is_dir($dir)) {
        mkdir($dir, 0755, true);
    }
    file_put_contents($path, $content);
}
