name: Static Analysis

on:
  push:
    branches: [trunk]
  pull_request:

jobs:
  phpstan:
    name: PHPStan (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4', '8.2']
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo, pdo_mysql, json, hash, zlib, mbstring

      - run: composer install --no-interaction --prefer-dist

      - run: composer analyze
