name: Static Analysis

on:
  push:
    branches: [trunk]
  pull_request:

jobs:
  phpstan:
    if: false  # Temporarily disabled while testing Playground CLI e2e
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: pdo, pdo_mysql, json, hash, zlib, mbstring

      - run: composer install --no-interaction --prefer-dist

      - run: composer analyze
